name: Build Quest Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual trigger from your iPhone

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup qpm-rust
      uses: Fernthedev/qpm-rust-action@main
      with:
        # Version of qpm-rust to use
        qpm_version: 'v0.1.1'

    - name: QPM Restore
      run: qpm restore

    - name: List files (Debug)
      run: ls -R

    - name: Build Mod
      run: qpm sbuild

    - name: Create QMOD
      run: qpm qmod build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Vivify-Quest-Build
        path: |
          ./build/*.so
          ./*.qmod
