name: Build Quest Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

# This gives the runner permission to download dependencies and upload artifacts
permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup qpm-rust
      uses: Fernthedev/qpm-rust-action@main
      with:
        # REQUIRED: This provides the auth token needed by the toolchain
        workflow_token: ${{ secrets.GITHUB_TOKEN }}
        version: 'v0.1.1' 
        restore: true
        qpm_qmod: true

    - name: Build Mod
      run: |
        qpm sbuild
        qpm qmod build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Vivify-Quest-Build
        path: |
          ./**/*.so
          ./*.qmod
